name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Set up pnpm
        run: |
          npm i -g pnpm@10.2.0
          pnpm i
      - name: Format
        run: pnpm format:check
      - name: Build frontend
        run: pnpm generate
